project:
  type: website
  output-dir: docs
  
website:
  favicon: img/favicon.png
  title: "Kevin R. Bairos-Novak"
  site-url: "https://ecolology.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
        # text: "{{< animate fadeInDown 'Home' delay=.5s >}}"
      - href: research.qmd
        text: Research
        # text: "{{< animate fadeInDown 'Research' delay=1s >}}"
      - href: posts.qmd
        text: Blog
        # text: "{{< animate fadeInDown 'Blog posts' delay=2s >}}" # add your posts.qmd file to your navbar!
      - href: art.qmd
        text: Pour paintings
        # text: "{{< animate fadeInDown 'Paintings' delay=3s >}}" # add your posts.qmd file to your navbar!
    right:
      - text: "{{< iconify fa6-brands researchgate >}}"
        href: "https://www.researchgate.net/profile/Kevin-Bairos-Novak/"
      # - icon: twitter
      #   href: "https://twitter.com/"
      
      - icon: "{{< iconify fa6-brands github >}}"
        href: "https://github.com/ecolology/kevin-r-bairos-novak"
      # - text: "{{< iconify fa6-brands linkedin >}}"
      #   href: "https://www.linkedin.com/in/mickaelcanouil"
  page-footer:
    # right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Kevin R. Bairos-Novak, 2023"

format:
  html:
    theme: minty
    toc: true

# filters:
#   - webr

editor: source

